apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "bookinfo.com"
  gateways:
  - mygateway
  http:
  - match:
    - uri:
        prefix: "/productpage"
    delegate:    # <------------
       name: productpage
       namespace: default
  - name: "reviews-routes"
    match:
    - uri:
        prefix: "/reviews"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: reviews-svc.default.svc.cluster.local

# delegate vsvc
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
  namespace: default
spec:
  http:
  - route:
    - destination:
        host: productpage-svc.default.svc.cluster.local
    rewrite:
      uri: "/"

# gateway

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"