apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
spec:
  selector:
    matchLabels:
      app: reviews
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: nginx
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello reviews > /usr/share/nginx/html/index.html"]

---
apiVersion: v1
kind: Service
metadata:
  name: reviews-svc
  labels:
    app: reviews
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: reviews